# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- azure-pipelines

pool: my-laptop-pool

steps:
- script: |
    docker build -t henryylim01/flask-app:$(Build.BuildNumber) .
  displayName: 'Build Docker image'

- script: |
    docker push henryylim01/flask-app:$(Build.BuildNumber)
  displayName: 'Push Docker image'

- script: |
    kubectl set image deployment/flask-app-deployment flask-app=henryylim01/flask-app:$(Build.BuildNumber) -n default
  displayName: 'Deploy to Kubernetes'

- script: |
    rm -rf $(Agent.BuildDirectory)/*
  displayName: 'Cleanup workspace'